version: "3.9"

services:
  backend:
    build: ./backend
    container_name: ss-backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - GPU_WORKER_URL=http://52.6.208.138:8001/process
    volumes:
      - media_data:/app/media
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: ss-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://52.55.198.180:8000/api
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  media_data:
